kubeProxyReplacement: true
k8sServiceHost: 127.0.0.1
k8sServicePort: 6443
operator:
  replicas: 1
envoy:
  enabled: true
debug:
  enable: true
  verbose: envoy
l2announcements:
  enabled: true
bgpControlPlane:
  enabled: true
# devices: "eth0"
externalIPs:
  enabled: true
nodePort:
  enabled: true
gatewayAPI:
  enabled: true
# ipam:
#   mode: kubernetes
bpf:
  masquerade: true
  hostLegacyRouting: false
ipv4:
  enabled: true
ipv6:
  enabled: false
image:
  pullPolicy: IfNotPresent
hubble:
  enabled: true
  ui:
    enabled: true
  relay:
    enabled: true
